"""
Common GitHub utility functions.
This module contains shared utilities used across different GitHub services.
"""
import re
from datetime import datetime
from typing import Dict, Any


def sanitize_repo_name(name: str) -> str:
    """
    Sanitize repository name to meet GitHub requirements.
    
    - Lowercase
    - Replace spaces and special chars with hyphens
    - Remove consecutive hyphens
    - Max 100 characters
    
    Args:
        name: Original project/repository name
        
    Returns:
        Sanitized name valid for GitHub
        
    Examples:
        >>> sanitize_repo_name("My Cool Project!")
        'my-cool-project'
        >>> sanitize_repo_name("Test___Project   123")
        'test-project-123'
    """
    # Lowercase
    sanitized = name.lower()
    
    # Replace spaces and special chars with hyphens
    sanitized = re.sub(r'[^a-z0-9-_.]', '-', sanitized)
    
    # Remove consecutive hyphens
    sanitized = re.sub(r'-+', '-', sanitized)
    
    # Remove leading/trailing hyphens
    sanitized = sanitized.strip('-')
    
    # Max 100 characters
    sanitized = sanitized[:100]
    
    # Ensure not empty
    if not sanitized:
        sanitized = f"project-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
    
    return sanitized


def generate_pr_body(
    solution: Any,
    user_info: Dict[str, str],
    files_count: int,
    commit_messages: list = None
) -> str:
    """
    Generate a professional Pull Request body with template.
    
    Args:
        solution: Solution object with task relationship
        user_info: Dictionary with user information (github_username, username)
        files_count: Number of files modified/added
        commit_messages: Optional list of commit messages
        
    Returns:
        Formatted PR body text
    """
    if commit_messages is None:
        commit_messages = []
        
    task = solution.task
    
    body = f"""## 🚀 Solution Submission

**Submitted by:** @{user_info.get('github_username') or user_info['username']}  
**Task:** #{solution.task_id} - {task.title}  
**Category:** {solution.contribution_category or 'code'}  

### 📝 Description

{solution.solution_content}

### 📊 Changes Summary

- **Files modified/added:** {files_count}
- **Contribution type:** {solution.contribution_category or 'General'}

### 🔍 Task Details

**Type:** {task.task_type}  
**Difficulty:** {task.difficulty}  
**Phase:** {task.phase}  

**Original Task Description:**
> {task.description[:500]}{'...' if len(task.description) > 500 else ''}

---
"""
    
    if commit_messages:
        body += "\n### 📦 Commits in this PR\n\n"
        # Add first 10 commits
        for i, msg in enumerate(commit_messages[:10], 1):
            body += f"{i}. {msg}\n"
        
        if len(commit_messages) > 10:
            body += f"\n...and {len(commit_messages) - 10} more commits\n"
    
    body += f"""
---

**🤖 Auto-generated by KICKTHISUSS Platform**  
*This pull request was automatically created from a solution submission.*  
*Task URL: [View Task Details](https://kickthisuss.com/tasks/{solution.task_id})*
"""
    
    return body


def generate_simple_pr_body(solution_data: Dict[str, Any]) -> str:
    """
    Generate a simple PR body from solution data dictionary.
    
    Args:
        solution_data: Dictionary with solution information
        
    Returns:
        Formatted PR body text
    """
    body = f"""## Solution Proposal

**Description:**
{solution_data.get('description', 'No description provided')}

**Category:** {solution_data.get('category', 'Uncategorized')}
**Author:** {solution_data.get('author', 'Anonymous')}
**Submitted:** {datetime.now().strftime('%Y-%m-%d %H:%M')}

---
*This PR was automatically generated by KickThisUSS*
"""
    return body
