"""Add 2FA fields to User model

Revision ID: 163d41bc6a4f
Revises: 9498c208a39c
Create Date: 2025-08-04 22:37:07.287547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163d41bc6a4f'
down_revision = '9498c208a39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
        batch_op.add_column(sa.Column('backup_codes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('backup_codes')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
