"""Add ProjectEquity table for detailed equity tracking

Revision ID: 1c7db9a3614c
Revises: 380cbc1f15a6
Create Date: 2025-10-09 21:48:43.323923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7db9a3614c'
down_revision = '380cbc1f15a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_equity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equity_percentage', sa.Float(), nullable=False),
    sa.Column('earned_from', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='_project_user_equity_uc')
    )
    with op.batch_alter_table('project_equity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_equity_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_equity_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_equity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_equity_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_equity_project_id'))

    op.drop_table('project_equity')
    # ### end Alembic commands ###
