"""Add EquityHistory table for audit log

Revision ID: 2e4c6a7d5fb0
Revises: 1c7db9a3614c
Create Date: 2025-10-09 22:02:53.215666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4c6a7d5fb0'
down_revision = '1c7db9a3614c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('equity_change', sa.Float(), nullable=False),
    sa.Column('equity_before', sa.Float(), nullable=False),
    sa.Column('equity_after', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equity_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equity_history_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_equity_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_equity_history_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equity_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equity_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equity_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_equity_history_project_id'))
        batch_op.drop_index(batch_op.f('ix_equity_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_equity_history_action'))

    op.drop_table('equity_history')
    # ### end Alembic commands ###
