"""Simplify GitHub integration - remove unused fields

Revision ID: 380cbc1f15a6
Revises: f5e07ab1c475
Create Date: 2025-10-09 21:21:04.944589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380cbc1f15a6'
down_revision = 'f5e07ab1c475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('github_sync_enabled')
        batch_op.drop_column('github_url')
        batch_op.drop_column('github_last_sync')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_last_sync', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('github_sync_enabled', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
