"""Add GitHub PR tracking and contribution analytics to Solution

Revision ID: 3e85c6276b1b
Revises: 09f5f9725c0f
Create Date: 2025-11-02 15:22:42.253264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e85c6276b1b'
down_revision = '09f5f9725c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_pr_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('github_branch', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('github_pr_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('github_commit_sha', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contribution_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('files_modified', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('files_added', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lines_added', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lines_deleted', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_solution_contribution_category'), ['contribution_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_solution_github_pr_number'), ['github_pr_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solution_github_pr_number'))
        batch_op.drop_index(batch_op.f('ix_solution_contribution_category'))
        batch_op.drop_column('lines_deleted')
        batch_op.drop_column('lines_added')
        batch_op.drop_column('files_added')
        batch_op.drop_column('files_modified')
        batch_op.drop_column('contribution_category')
        batch_op.drop_column('github_commit_sha')
        batch_op.drop_column('github_pr_status')
        batch_op.drop_column('github_branch')
        batch_op.drop_column('github_pr_number')

    # ### end Alembic commands ###
