"""add_content_type_to_free_proposals

Revision ID: 56044f466cae
Revises: 4cd333c1bb31
Create Date: 2025-11-02 12:00:35.258648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56044f466cae'
down_revision = '4cd333c1bb31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('free_proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('publish_method', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('implementation_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('primary_file_path', sa.String(length=2048), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_index('idx_free_proposals_developer')
        batch_op.drop_index('idx_free_proposals_project')
        batch_op.drop_index('idx_free_proposals_status')
        batch_op.create_index(batch_op.f('ix_free_proposals_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_proposals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_proposals_developer_id'), ['developer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_proposals_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_proposals_proposal_type'), ['proposal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_proposals_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('free_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_free_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_free_proposals_proposal_type'))
        batch_op.drop_index(batch_op.f('ix_free_proposals_project_id'))
        batch_op.drop_index(batch_op.f('ix_free_proposals_developer_id'))
        batch_op.drop_index(batch_op.f('ix_free_proposals_created_at'))
        batch_op.drop_index(batch_op.f('ix_free_proposals_content_type'))
        batch_op.create_index('idx_free_proposals_status', ['status'], unique=False)
        batch_op.create_index('idx_free_proposals_project', ['project_id'], unique=False)
        batch_op.create_index('idx_free_proposals_developer', ['developer_id'], unique=False)
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('primary_file_path')
        batch_op.drop_column('implementation_details')
        batch_op.drop_column('publish_method')
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
