"""Add Wiki, Strategic Objectives, and Validation Tasks

Revision ID: 7fa25f1e4cea
Revises: e44a6d724f5c
Create Date: 2025-07-17 21:38:20.115661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa25f1e4cea'
down_revision = 'e44a6d724f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hypothesis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('test_method', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('results', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('results')
        batch_op.drop_column('test_method')
        batch_op.drop_column('hypothesis')

    # ### end Alembic commands ###
