"""Fix project_type field default and constraints

Revision ID: d46accc04aad
Revises: 0f82599b5d41
Create Date: 2025-09-06 15:59:15.050844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46accc04aad'
down_revision = '0f82599b5d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('project_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('creator_equity',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_project_project_type'), ['project_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_project_type'))
        batch_op.alter_column('creator_equity',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('project_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
