"""Add GitHub fields to Task model

Revision ID: 09f5f9725c0f
Revises: 56044f466cae
Create Date: 2025-11-02 13:41:29.968919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f5f9725c0f'
down_revision = '56044f466cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_issue_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('github_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('github_synced_at')
        batch_op.drop_column('github_issue_number')

    # ### end Alembic commands ###
