"""Add AI fields to Project model

Revision ID: 0b2e3b3e47d5
Revises: dc496d1162e7
Create Date: 2025-08-02 18:07:28.307518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2e3b3e47d5'
down_revision = 'dc496d1162e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_mvp_guide', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_feasibility_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_guide_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('ai_guide_generated_at')
        batch_op.drop_column('ai_feasibility_analysis')
        batch_op.drop_column('ai_mvp_guide')

    # ### end Alembic commands ###
