"""Remove strategic mapping functionality

Revision ID: 3bcee2bd88d4
Revises: 9cc33996114d
Create Date: 2025-07-21 21:28:11.099863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bcee2bd88d4'
down_revision = '9cc33996114d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategic_objective', schema=None) as batch_op:
        batch_op.drop_index('ix_strategic_objective_created_by')
        batch_op.drop_index('ix_strategic_objective_parent_id')
        batch_op.drop_index('ix_strategic_objective_project_id')

    op.drop_table('strategic_objective')
    op.drop_table('objective_task_link')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('position_y')
        batch_op.drop_column('position_x')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_x', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('position_y', sa.FLOAT(), nullable=True))

    op.create_table('objective_task_link',
    sa.Column('objective_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['strategic_objective.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('objective_id', 'task_id')
    )
    op.create_table('strategic_objective',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('position_x', sa.FLOAT(), nullable=True),
    sa.Column('position_y', sa.FLOAT(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('is_root', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['strategic_objective.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategic_objective', schema=None) as batch_op:
        batch_op.create_index('ix_strategic_objective_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_strategic_objective_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('ix_strategic_objective_created_by', ['created_by'], unique=False)

    # ### end Alembic commands ###
