"""Add GitHub workflow and hardware submission features

Revision ID: dc496d1162e7
Revises: 3bcee2bd88d4
Create Date: 2025-07-21 21:36:29.758775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc496d1162e7'
down_revision = '3bcee2bd88d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pull_request_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_column('pull_request_url')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('github_url')

    # ### end Alembic commands ###
