"""Add GitHub integration fields to Project model

Revision ID: f5e07ab1c475
Revises: d46accc04aad
Create Date: 2025-10-09 21:11:49.844311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e07ab1c475'
down_revision = 'd46accc04aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_repo_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('github_sync_enabled', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('github_last_sync', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_project_github_repo_name'), ['github_repo_name'], unique=False)

    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solution_content_type'), ['content_type'], unique=False)

    with op.batch_alter_table('solution_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solution_file_content_type'), ['content_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solution_file_content_type'))

    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solution_content_type'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_github_repo_name'))
        batch_op.drop_column('github_last_sync')
        batch_op.drop_column('github_sync_enabled')
        batch_op.drop_column('github_repo_name')

    # ### end Alembic commands ###
