"""Add platform_fee to Project

Revision ID: fdfb86f1dab0
Revises: 
Create Date: 2025-07-14 20:45:10.894017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfb86f1dab0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_fee', sa.Float(), nullable=False, server_default='1.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('platform_fee')

    # ### end Alembic commands ###
